kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
resources:
- ../base
namePrefix: reddit-
commonLabels:
  app: reddit
images:
- name: grab
  newName: atdr.meo.ws/archiveteam/reddit-grab



# add anti affinity to not run on the same node
patches:
- target:
    kind: Deployment
  patch: |-
    - op: add
      path: /spec/template/spec/affinity
      value:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - reddit
            topologyKey: kubernetes.io/hostname
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/master
                operator: DoesNotExist
    - op: add
      path: /spec/replicas
      value: 5
    - op: add
      path: /spec/template/spec/containers/0/env/-
      value:
        name: CONCURRENT
        value: "5"
